/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface IntentBodySchema {
  payment_method?: string;
  amount: number;
  currency: string;
  confirmation_method?: string;
  confirm?: boolean;
  setup_future_usage?: string;
  capture_method?: string;
  customer?: string;
  payment_method_types?: string[];
  [k: string]: unknown;
}
